# Github Setup {-}

Before the first day of class, you should follow these instructions to set up the collaboration/version control software that we'll be using throughout the semester. You'll collaborate with others and submit assignments through Github and Github Classroom. If you aren't familiar with Git or Github, here are brief explanations of these technologies. 

Git: a version control software typically run in the shell/terminal of your computer that helps you keep track of the history of a document (updates, changes, etc.)
Github: an online repository platform that facilitates collaboration between individuals and provides a space for you to showcase your work to others. 

Here are some steps to take (that you'll only have to do once!). Please let me know if you have any issues going through these steps:

1. If you don't already have one, please create a Github account/username. Go to https://github.com and register an account (if you don't have one already).

- You'll need to choose a username at this time. Think carefully about this because you may keep this account for a LONG time. Try to incorporate your actual name in it. Reuse usernames from other accounts such as Twitter. Pick a username you'd be ok sharing with future employers. Shorter is better. Make it timeless. Avoid names with words that have special meaning in programming. 

2. Go to https://education.github.com/students to sign up for student benefits such as unlimited private repositories through Github Education.

3. Please fill out this [Google Form](https://forms.gle/5SmoZkLCwi2wtVda8) with your name and Github username.

4. Install Git on your machine (Instructions here: https://happygitwithr.com/install-git.html).

5. Provide your local Git with your name and email -- same that you used for Github (Instructions here, you can stop before 7.1: https://happygitwithr.com/hello-git.html)

6. Download a Git client (GUI) so that you don't have to work with the shell/terminal if you don't want to. I use Github Desktop (https://desktop.github.com/) but there are some who have had issues with the one. There are other recommendations here (https://happygitwithr.com/git-client.html), but I haven't used them personally.

7. Go to your Github.com account and make a new repository. Give it a name, provide a description, make it public, and initialize a README file. Copy the URL via the "Clone or Download" button. Now clone that repository to your local machine by going to your shell/terminal and go to your Desktop folder (type: `cd ~/Desktop`). Then type: `git clone https://github.com/THEURLYOUJUSTCOPIED`

8. Cache credentials for HTTPS so you don't have to input your github username and password each time to pass information between the local machine and the online repository. Your Git client (such as Github Desktop) will do this for you or you can do it with the shell/terminal (Instructions: https://happygitwithr.com/https-pat.html)

I want to make sure to get ahead of any technology issues (they will happen as they always do), so please email me if you encounter any issues!

