# (PART) Technology {-}
# R and RStudio Setup {-}

Before the first day of class, you should follow these instructions to set up the software that we'll be using throughout the semester. **Even if you've already downloaded both R and RStudio, you'll want to re-download to make sure that you have the most current versions.**

*Highly* recommended: Change the default file download location for your internet browser.

- Generally by default, internet browsers automatically save all files to the `Downloads` folder on your computer. This does not encourage good file organization practices. It is highly recommended that you change this option so that your browser asks you where to save each file before downloading it.
- This [page](https://www.online-tech-tips.com/computer-tips/change-default-download-folder-location-on-any-web-browser/) has information on how to do this for the most common browsers.

<br>

**Required:** Download R and RStudio

- **FIRST:** Download R [here](https://cran.r-project.org/).
    - You will see three links "Download R for ..."
    - Choose the link that corresponds to your computer.
    - As of Jan 4, 2022, the latest version of R is 4.1.2.
- **SECOND:** Download RStudio [here](https://rstudio.com/products/rstudio/download/#download).
    - Click the button under step 2 to install the version of RStudio recommended for your computer.
    - As of Jan 4, 2022, the latest version of RStudio is 2021.09.14+372.

<br>

**Highly Recommended:** Watch this [video](https://www.youtube.com/watch?v=LJiRSPoe8r0) made by Professor Lisa Lendway that describes essential configuration options for RStudio.

<br>

**Required:** Install the most up-to-date versions of the required **R packages** for this course.

- An R **package** is an extra bit of functionality that will help us in our data analysis efforts in a variety of ways.
- Open RStudio and click inside the Console pane (by default, the bottom left pane). Copy and paste the following command into the Console. You should see the text below appear to the right of the `> `, which is called the **R prompt**. After you paste, hit Enter.

```{r eval=FALSE}
    install.packages(c("ggplot2", "dplyr", "readr","tidyr", "rmarkdown", "broom", "astsa","geepack","gee","geeM"))
```

- If you get a message that says "There are binary versions available the source versions are later"" type `no` and press Enter.
- You will see a lot of text from status messages appearing in the Console as the packages are being installed. Wait until you see the `> ` again.
- Enter the command `library(ggplot2)` and hit enter.    
    If you see the message `Error in library(ggplot2) : there is no package called ggplot2`, then there was a problem installing this package. Jump down to the Troubleshooting section below. (Any other messages that appear are fine, and a lack of any messages is also fine.)
- Repeat the above step for the commands:
    - `library(dplyr)`
    - `library(readr)`
    - `library(rmarkdown)`
    - `library(tidyr)`
    - `library(broom)`
    - `library(astsa)`
    - `library(geepack)`
    - `library(gee)`
    - `library(geeM)`
- Quit RStudio. You're done setting up!

**Optional:**  For a refresher on RStudio features, watch this [video](https://www.youtube.com/watch?v=HWnanydsBCs). It also shows you how to customize the layout and color scheme of RStudio.

<br><br>

## Troubleshooting {-}

- **Problem:** You are on a Mac and getting the following error:    
```
    Error: package or namespace load failed for ‘ggplot2’ in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]):
     there is no package called ‘rlang’
```    
    Here's how to fix it:
    - First install the suite of Command Line Tools for Mac using the instructions [here](http://osxdaily.com/2014/02/12/install-command-line-tools-mac-os-x/).
    - Next enter `install.packages("rlang")` in the Console.
    - Finally check that entering `library(ggplot2)` gives no errors.

